# Generated by Django 4.2.1 on 2023-07-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0002_fooditems'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditems',
            name='availability',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditems',
            name='category_ids',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditems',
            name='group_ids',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(upload_to='images/categories'),
        ),
    ]
